baseURL = 'https://bron.sh/'
title = 'bron'
theme = 'hugo-book'

# Book configuration
disablePathToLower = true
enableGitInfo = false

disableKinds = ['taxonomy']

[module]
  [[module.imports]]
    path = 'github.com/hugomods/icons/vendors/lucide'

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[markup.highlight]
  noClasses = false
  style = 'pygments'
  tabWidth = 4

[menu]
[[menu.before]]
  name = "Introduction"
  pageRef = '/'
  weight = 10
[[menu.after]]
  name = "Github"
  url = "https://github.com/thijsmie/bron"
  weight = 10

[params]
  BookTheme = 'light'
  BookToC = true
  BookLogo = 'svg/bron.svg'
  BookSection = '/'
  BookRepo = 'https://github.com/thijsmie/bron'
  BookEditPath = 'edit/main/site'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true

  # /!\ These are experimental features
  BookPortableLinks = true
  BookServiceWorker = true


  

