[project]
dependencies = [
    "packaging>=24.2",
    "pytoml11>=0.0.2",
    "typer>=0.15.1",
]
description = "Operational TOML"
name = "tomly"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"

[project.scripts]
tomly = "tomly:app"

[tool.uv]
package = true

